import Ui from "@/components/Ui";
import Head from "next/head";
import { configureStore } from "@reduxjs/toolkit";
import { Provider } from "react-redux";
import userReducer from "../features/user";
import themeReducer from "../features/theme";

const store = configureStore({
  reducer: {
    user: userReducer,
    theme: themeReducer,
  },
});

const Home = () => {
  return (
    <>
      <Head>
        <title>Tic Toe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Provider store={store}>
          <Ui />
        </Provider>
      </main>
    </>
  );
};

export default Home;
